// This file is automatically generated. Do not modify it manually.
// This file is automatically generated. Do not modify it manually.
// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "mock-project-id-12345.firebaseapp.com",
  "projectId": "mock-project-id-12345",
  "storageBucket": "mock-project-id-12345.appspot.com",
  "messagingSenderId": "123456789012",
  "appId": "1:123456789012:web:mock-app-id-abcdef123456",
  "measurementId": "G-MOCK123456"
};