// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  apiKey: "AIzaSyAHDYayuejWZhybP8zyu7L_GmUr_2zAFsk",
  authDomain: "dailyneeds-tracker-9fkv2.firebaseapp.com",
  projectId: "dailyneeds-tracker-9fkv2",
  storageBucket: "dailyneeds-tracker-9fkv2.firebasestorage.app",
  messagingSenderId: "510600081385",
  appId: "1:510600081385:web:0d7d1f2fc228e8eb8fa578",
  measurementId: "G-N9RS5YD7KF",
};
